# Generated by Django 4.2 on 2025-02-06 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sparta_furniture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.IntegerField()),
                ('product_stock', models.IntegerField()),
                ('sparta_furniture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='sparta_furniture.spartafurniture')),
            ],
        ),
    ]
