# Generated by Django 4.2 on 2025-02-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_create_at', models.DateField()),
                ('customer_tel', models.CharField(max_length=50)),
            ],
        ),
    ]
