# Generated by Django 4.2 on 2025-02-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_create_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
