# Generated by Django 4.2 on 2025-02-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpartaFurniture',
            fields=[
                ('sparta_furniture_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sparta_furniture_location', models.CharField(max_length=50)),
                ('sparta_furniture_manager', models.CharField(max_length=50)),
                ('sparta_furniture_tel', models.CharField(max_length=50)),
                ('sparta_furniture_open', models.DateField()),
                ('sparta_staff_num', models.IntegerField()),
            ],
        ),
    ]
