# Generated by Django 4.2 on 2025-02-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparta_furniture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spartafurniture',
            name='sparta_furniture_open',
            field=models.DateField(auto_now_add=True),
        ),
    ]
